version: "3.8"
services:
  catelogdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  rabbitmq:
    image: rabbitmq:4.0.7-management


volumes:
  catelogdb_volume:
  discount_volume:
  identitydb_volume:
  orderdb_volume: