FROM mcr.microsoft.com/dotnet/sdk:8.0-buster-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/FreeCourse.Shared/*.csproj Shared/FreeCourse.Shared/
COPY Services/Catelog/FreeCourse.Services.Catelog/*.csproj Services/Catelog/FreeCourse.Services.Catelog/
RUN dotnet restore Services/Catalog/FreeCourse.Services.Catelog/*.csproj
COPY . .
RUN dotnet publish Services/Catelog/FreeCourse.Services.Catelog/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:8.0-buster-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","FreeCourse.Services.Catelog.dll" ]